// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjij9sOAdPNSEwqyQeopC02dbQ2gEaX_U',
    appId: '1:194892358407:web:8919109ec1692c86fa5ba2',
    messagingSenderId: '194892358407',
    projectId: 'patrimonia-sim',
    authDomain: 'patrimonia-sim.firebaseapp.com',
    storageBucket: 'patrimonia-sim.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnckVSmdSL9ICMS0Qdc1-keJfPQW96gaw',
    appId: '1:194892358407:android:2068cf50303685aefa5ba2',
    messagingSenderId: '194892358407',
    projectId: 'patrimonia-sim',
    storageBucket: 'patrimonia-sim.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTvKqfwgc95TKvga-T4GQun_g9HWSiEls',
    appId: '1:194892358407:ios:3a0531f3ba938d0bfa5ba2',
    messagingSenderId: '194892358407',
    projectId: 'patrimonia-sim',
    storageBucket: 'patrimonia-sim.firebasestorage.app',
    iosBundleId: 'app.simulateur.simulateurCredits',
  );
}
